apiVersion: v1
kind: Service
metadata:
  name: helloworld-ui
  namespace: default
spec:
  type: NodePort
  selector:
    app: helloworld-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31000 
