apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helloworld-ui
  template:
    metadata:
      labels:
        app: helloworld-ui
    spec:
      containers:
      - image: ryuisanggo/myhelloworld:50
        name: helloworld-ui
        ports:
        - containerPort: 5000
